# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: pre-commit

'on':
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v2.0.0
